from LinguaPythonica.Laspak.Root import LaspakRoot

roots_input = [
    # Rajouter dans cet ordre :
    # letter1, letter2, letter3, traduction
    ('Q','CH','N','feu',),
    ('G','L','R','froid',),
    ('B','K','R','foudre',),
    ('V','T','L','eau',),
    ('D','W','L','vie / existence',),
    ('X','S','F','vision',),
    ('L','L','N','magie',),
    ('TH','N','M','lumière',),
    ('K','R','B','pierre/roche',),
    ('M','CH','R','mouvement',),
    ('S','L','R','agilité/souplesse',),
    ('H','M','N','conscience',),
    ('Y','D','K','corps/chair',),
    ('T','Y','R','vol',),
    ('R','L','TH','chant',),
    ('V','X','S','vent',),
    ('N','L','M','léthargie (fatigue ++)',),
    ('CH','M','L','début',),
    ('G','G','N','répétition',),
    ('P','D','T','rapidité',),
    ('F','S','K','fleur',),
    ('W','S','N','joie',),
    ('S','P','K','parole',),
    ('Q','W','K','force',),
    ('M','R','R','dégoût',),
    ('L','V','T','mémoire',),
    ('F','Q','L','hauteur',),
    ('H','R','R','rouge',),
    ('B','R','N','orange',),
    ('S','J','Y','jaune',),
    ('X','V','K','vert',),
    ('Z','B','TH','bleu',),
    ('B','V','P','violet',),
    ('Y','B','W','blanc',),
    ('D','G','R','gris',),
    ('N','M','B','marron',),
    ('K','N','B','noir',),
    ('TH','R','P','rose',),
    ('TH','Z','T','totalité',),
    ('N','B','L','grandeur',),
    ('G','R','TH','terre',),
    ('G','M','TH','glace',),
    ('G','Z','H','cendres',),
    ('Q','Z','L','fumée',),
    ('CH','N','F','poussière',),
    ('Z','P','Z','sel',),
    ('Z','K','S','sable',),
    ('G','Y','TH','journée',),
    ('L','CH','Y','nuit',),
    ('P','L','N','nuage',),
    ('R','W','G','gentillesse',),
    ('P','H','G','jeunesse',),
    ('TH','J','L','neige',),
    ('W','D','H','unicité',),
    ('F','K','M','similarité',),
    ('S','P','K','parole',),
    ('F','L','T','platitude',),
    ('L','Q','T','découverte',),
    ('S','T','Y','permanence physique',),
    ('B','L','D','ville',),
    ('K','R','J','motivation',),
    ('T','H','B','argile',),
    ('L','S','Q','colle',),
    ('J','K','B','construction',),
    ('M','S','S','atteinte',),
    ('Z','N','L','zone',),
    ('S','M','K','identité',),
    ('J','T','M','regroupement',),
    ('W','L','D','parenté / ascendance',),
    ('Q','R','B','proximité',),
    ('M','L','F','achèvement',),
    ('W','W','N','aide',),
    ('P','R','V','prévoyance / projection',),
    ('K','L','F','clarté',),
    ('F','L','M','compréhension',),
    ('K','Q','S','conséquence',),
    ('Z','M','N','temps',),
    ('S','G','R','sang',),
    ('D','S','R','laine',),
    ('TH','K','R','pensée',),
    ('H','B','B','volonté de faire',),
    ('Z','K','S','raison / excuse',),
    ('S','P','D','possession / appartenance',),
    ('X','Y','B','tare / souillure',),
    ('S','B','D','esclavagisme',),
    ('N','G','N','négation',),
    ('CH','H','R','saison',),
    ('R','T','S','vérité',),
    ('N','B','T','plante',),
    ('W','D','D','bois',),
    ('CH','B','R','charbon',),
    ('L','M','T','métal',),
    ('M','H','M','intérêt (porté à un sujet)',),
    ('S','K','N','pitié',),
    ('G','R','S','attaque / aggressivité',),
    ('V','B','R','apprivoisement',),
    ('Y','M','N','paix',),
    ('H','V','N','obligation',),
    ('V','CH','Q','traversée',),
    ('R','M','F','réflexion / reflet',),
    ('M','B','R','ombre',),
    ('V','R','T','ouverture / écartement',),
    ('CH','S','K','cause',),
    ('X','F','CH','peur',),
    ('M','N','S','émotion',),
    ('Z','J','L','séisme',),
    ('L','K','N','lien / connexion',),
    ('N','R','V','colère',),
    ('Q','CH','K','précision',),
    ('CH','P','N','champignon',),
    ('R','K','T','cristal',),
    ('V','H','N','honneur',),
    ('W','P','R','fierté',),
    ('L','D','Q','spécialité / extra-normalité',),
    ('TH','W','CH','vide / absence',),
    ('M','T','R','mystère',),
    ('T','M','M','perte',),
    ('S','N','S','sens (de qqch)',),
    ('D','J','R','direction (dirigier qqch)',),
    ('S','F','R','trou',),
    ('Z','L','L','imposant.SUBS',),
    ('T','S','N','attention',),
    ('M','N','D','demande / exigence',),
    ('P','D','R','possibilité',),
    ('W','R','P','prêt.SUBS',),
    ('R','G','L','gratitude',),
    ('TH','Y','Q','confiance',),
    ('M','S','M','clémence',),
    ('J','D','N','nouveauté',),
    ('V','P','R','épreuve',),
    ('T','N','S','attente',),
    ('K','R','Z','croisement/rencontre',),
    ('S','V','R','découverte',),
    ('TH','N','S','clémence',),
    ('G','B','L','liane/fouet',),
    ('J','R','R','tourbillon',),
    ('H','R','J','arme',),
    ('X','L','B','extraction',),
    ('F','L','N','sensation',),
    ('L','CH','R','flux (mouvement passif)',),
    ('S','H','B','amitié',),
    ('M','R','CH','son',),
    ('V','Q','F','verticalité / redressement',),
    ('S','K','R','écriture',),
    ('F','R','M','affirmation',),
    ('N','N','S','bonté',),
    ('S','L','N','essence (être)',),
    ('V','H','Q','croyance',),
    ('G','Z','R','chance',),
    ('M','H','T','douleur',),
]

# On assemble ici toutes les racines
LASPAK_ROOTS = [LaspakRoot(letter1=tup[0],letter2=tup[1],letter3=tup[2],translation=tup[3]) for tup in roots_input]